// import companyData from './company_columnar.json';
// import umlData from './uml_columnar.json';
// import millImpactData from './data_by_mill_columnar.json';

export type UmlData = {
  "UML ID": string,
  "Group Name": string,
  "Parent Company": string,
  "Mill Name": string,
  "RSPO Status": string,
  "RSPO Type": number | null,
  "Date RSPO Certification Status": string,
  "Latitude": number,
  "Longitude": number,
  "GPS coordinates": string,
  "ISO": string,
  "Country": string,
  "Province": string,
  "District": string,
  "Confidence level": string,
  "Alternative name": string | null,
  "area": number,
  "km_area": number,
  "km_forest_area_00": number,
  "ha_forest_area_00": number,
  "treeloss_km_2000": number,
  "treeloss_ha_2000": number,
  "treeloss_km_2001": number,
  "treeloss_ha_2001": number,
  "treeloss_km_2002": number,
  "treeloss_ha_2002": number,
  "treeloss_km_2003": number,
  "treeloss_ha_2003": number,
  "treeloss_km_2004": number,
  "treeloss_ha_2004": number,
  "treeloss_km_2005": number,
  "treeloss_ha_2005": number,
  "treeloss_km_2006": number,
  "treeloss_ha_2006": number,
  "treeloss_km_2007": number,
  "treeloss_ha_2007": number,
  "treeloss_km_2008": number,
  "treeloss_ha_2008": number,
  "treeloss_km_2009": number,
  "treeloss_ha_2009": number,
  "treeloss_km_2010": number,
  "treeloss_ha_2010": number,
  "treeloss_km_2011": number,
  "treeloss_ha_2011": number,
  "treeloss_km_2012": number,
  "treeloss_ha_2012": number,
  "treeloss_km_2013": number,
  "treeloss_ha_2013": number,
  "treeloss_km_2014": number,
  "treeloss_ha_2014": number,
  "treeloss_km_2015": number,
  "treeloss_ha_2015": number,
  "treeloss_km_2016": number,
  "treeloss_ha_2016": number,
  "treeloss_km_2017": number,
  "treeloss_ha_2017": number,
  "treeloss_km_2018": number,
  "treeloss_ha_2018": number,
  "treeloss_km_2019": number,
  "treeloss_ha_2019": number,
  "treeloss_km_2020": number,
  "treeloss_ha_2020": number,
  "treeloss_km_2021": number,
  "treeloss_ha_2021": number,
  "treeloss_km_2022": number,
  "treeloss_ha_2022": number,
  "sum_of_treeloss_km": number,
  "treeloss_sum_proportion_of_forest": number,
  "remaining_proportion_of_forest": number,
  "risk_score_current": string,
  "risk_score_past": string,
  "risk_score_future": string,
};

export type CompanyData = any;
export type MillImpactData = any;